### ISSUE TITLE
VPSIGNB is available AVX2 for applying weight

### ISSUE THREAD

**Issue by lithium0003** [catid/bitnet_cpu#1]
VPSIGNB __m256i _mm256_sign_epi8 (__m256i a, __m256i b)
https://www.felixcloutier.com/x86/psignb:psignw:psignd

This function can apply weight(+-1), so no divide weights to plus and minus.
``` c
o = _mm256_sign_epi8(a, b)
if(b == 0){
 o = 0
}
else if(b < 0){
 o = -a
}
else {
 o = a
}
```

This function may be help speed.

**Comment by catid** [comment]
This is great!  I'll give it a try.  This allows us to use 8 bits per parameter instead by preprocessing the weights to -1, 1, 0 bytes

**Comment by catid** [comment]
Landed this improvement, and it's huge!
